services:
  - type: web
    name: ocr-webapp
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn ocr_webapp.wsgi:application --timeout 120"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: MEDIA_ROOT
        value: /opt/render/project/src/media